[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.10"
name = "TFS"
dynamic = ["version", "description"]

dependencies = [
    "aiogram=2.24",
    "requests=2.28.1",
    "yadisk=1.2.1",
    "psycopg2-binary=2.9.5"
]
